<?php
//IP DE LA PC SERVIDOR DE LA BASE DE DATOS
define("DB_HOST","localhost");

//NOMBRE DE LA BASE DE DATOS
define("DB_NAME","uaem");

//USUARIO DE LA BASE DE DATOS
define("DB_USERNAME","root");

//CONTRASEÑA DEL USUARIO DE LA BASE DE DATOS
define("DB_PASSWORD","");

//DEFINIMOS LA CODIFICACION DE LOS CARACTERES
define("DB_ENCODE","utf8");

//DEFINIMOS UNA CONSTANTE CON EL NOMBRE DEL PROYECTO
define("PRO_NOMBRE","php");
?>